# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Car_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets;
from Car_selection import Car;


class Ui_MainWindow(Car):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 100, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(460, 80, 256, 331))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 100, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)

        self.pain_color_button = QtWidgets.QButtonGroup(MainWindow)
        self.pain_color_button.setObjectName("pain_color_button")

        self.wheels_button = QtWidgets.QButtonGroup(MainWindow)
        self.wheels_button.setObjectName("wheels_button")


        self.radioButton.setObjectName("radioButton")
        self.radioButton.setGeometry(QtCore.QRect(50, 190, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 230, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 270, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 140, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(270, 190, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(270, 230, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(270, 270, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 20, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)#,clicked = lambda :self.confirm_click())
        self.pushButton_3.setGeometry(QtCore.QRect(30, 340, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pain_color_button.addButton(self.radioButton)
        self.pain_color_button.addButton(self.radioButton_2)
        self.pain_color_button.addButton(self.radioButton_3)
        self.wheels_button.addButton(self.radioButton_4)
        self.wheels_button.addButton(self.radioButton_5)
        self.wheels_button.addButton(self.radioButton_6)

        self.pushButton.clicked.connect(self.model_select_audi)
        self.pushButton_2.clicked.connect(self.model_select_bmw)
        self.pushButton_3.clicked.connect(self.confirm_click)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Audi"))
        self.label.setText(_translate("MainWindow", "Select your car"))
        self.pushButton_2.setText(_translate("MainWindow", "BMW"))
        self.label_2.setText(_translate("MainWindow", "Choose your paint color"))
        self.radioButton.setText(_translate("MainWindow", "Red"))
        self.radioButton_2.setText(_translate("MainWindow", "Green"))
        self.radioButton_3.setText(_translate("MainWindow", "Blue"))
        self.label_3.setText(_translate("MainWindow", "Choose your Wheels"))
        self.radioButton_4.setText(_translate("MainWindow", "Sharp"))
        self.radioButton_5.setText(_translate("MainWindow", "Square"))
        self.radioButton_6.setText(_translate("MainWindow", "Circle"))
        self.label_4.setText(_translate("MainWindow", "Car Detail"))
        self.pushButton_3.setText(_translate("MainWindow", "Confirm"))

    def model_select_audi(self):
        self.model = "audi"
        self.calculate_price()
        self.textBrowser.setText(f"Mode: {self.model}\nPaint Color: {self.paint}\nWheel: {self.wheels}\nPrice: {self.price}")


    def model_select_bmw(self):
        self.model ="bmw"
        self.calculate_price()
        self.textBrowser.setText(f"Mode: {self.model}\nPaint Color: {self.paint}\nWheel: {self.wheels}\nPrice: {self.price}")




    def confirm_click(self):
         # wheel_price = {"sharp" :100, "circle":50, "square":20}
        if self.radioButton_4.isChecked():
            self.wheels = "sharp"
        if self.radioButton_5.isChecked():
            self.wheels = "circle"
        if self.radioButton_6.isChecked():
            self.wheels = "square"
        if self.radioButton.isChecked():
            self.paint = "red"
        if self.radioButton_2.isChecked():
            self.paint = "green"
        if self.radioButton_3.isChecked():
            self.paint = "blue"

        self.calculate_price()
        self.textBrowser.setText(f"Mode: {self.model}\nPaint Color: {self.paint}\nWheel: {self.wheels}\nPrice: {self.price}")




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
