# Generated by Django 4.1 on 2022-11-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection(title)
        VALUES('collection1')
        ""","""
        DELETE FROM sotre_colletion
        WHERE title = 'collection1'
        """)
    ]
